### PR TITLE
Webhook documentation update

### LINKED ISSUE #2203: Webhook Documentation
## Expected Behavior
Webhook documentation should (at a minimum) be up-to-date.
More webhook examples would also be useful.

## Current Behavior
Webhook documentation hasn't been (materially) updated since May 14th.

### PR DESCRIPTION
**Pull request by pogo-excalibur**
## Description
Updates the documentation for webhooks.

## Motivation and Context
The current documentation for webhooks doesn't include a great deal of detail, and in some cases is months out-of date (e.g. the references to `gym_defeated` and `gym_conquered` events).

Resolves #2203.

## Types of changes

- [x] Documentation update

### CODE REVIEW

**Comment by MARTINI1** [comment]
with so much elimination has been lost the list of valid types of webhook xD

it would be nice to put it back and with the new captcha type

by other hand, I see PR ok

**Comment by pogo-excalibur** [comment]
@MARTINI1 I've removed the list because I felt the descriptions of each webhook type were sufficient.

I've now add in a text-list (with each element linked to the appropriate section) where the table used to be (ish).

I've also added a table of contents, as the document is now quite long.

**Comment by sebastienvercammen** [comment]
@pogo-excalibur Could you rebase the PR?

**Comment by pogo-excalibur** [comment]
@sebastienvercammen now rebased

**Pull request merged**
