### PR TITLE
Display Worker Names

### PR DESCRIPTION
**Pull request by Janglinator**
Allows for displaying which specific worker scanned a search area.

## Description
I added storing the username of the account that scanned a specific point, and added displaying them on the map inside the scan circles.  The disappear when zoomed out past a point where displaying them is pointless (the text begins to overlap).

## Motivation and Context
We don't always know which account is giving us a hard time!  This just makes it quick and easy.

## How Has This Been Tested?
I did it, I saw account names, I celebrated.  🎉 

## Screenshots (if appropriate):
screen shot 2016-11-19 at 7 49 49 pm

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by Janglinator** [comment]
To continue discussions from a different thread:

**Comment by Janglinator** [comment]
@gonjiak It's working great, at a certain zoom level it, as intended, shows the assigned account name with random colours. But, at least for me, the CPU usage is really high, and it's a overkill for mobile devices if you use a local tunnel like ngrok. I suggest to make it optional or less resource hungry (or both).

**Comment by Janglinator** [comment]
@antistoopmode "There seems to be a bug where the labels are still being rendered after the "scanned location" is toggled off. I also experienced high CPU usage as @gonjiak already mentioned. In my opinion, the displaying of the username should be separated from the backend enhancement pull request."

**Comment by Janglinator** [comment]
@ simonbuehler "maybe the labels should be actually removed from the Map and not set to a whitespace when hiding"

**Comment by slideup-benni** [comment]
it it possible, that the names dous not disappear when the circle disappears?

**Comment by Janglinator** [comment]
@krkmastav As with any UI changes, always make sure to invoke `npm run build` before running the script

**Comment by Janglinator** [comment]
@slideup-benni That's exactly what I did wrong  :(  I'll get er patched tonight.

**Comment by Janglinator** [comment]
If anybody would like to work on this, let me know, I'll give you write access.  I've lost interest in pogo-map, and don't plan on continuing following it.

**Comment by onilton** [comment]
@Janglinator can you give me write access?

**Comment by sebastienvercammen** [comment]
We've asked around for contributors to pick up, or if anyone was interested in the PR, but it seems the answer is no. Closing until someone needs it and wants to update it.

**Pull request closed without merging**
