### PR TITLE
Use black color for gym-details text (avoid annyoing yellow instinct color)

### PR DESCRIPTION
**Pull request by lluisd**
Use black color for gym-details text (avoid annyoing yellow instinct color)

## Description
Use black color for all teams on the gym details slidebar. Keep a css selector for each time for future pruposes. 

## Motivation and Context
Red and Blue colors used in gym-details for Valor and Mystic teams are easy to read. But Instinct had the black color since 4 days ago when someone changes it to yellow as a text bug. I**t was not a bug, it's because yellow color is so dificult to read** when you are outside (sun is shining, your screen light is not 100%...) with your mobile. 

To keep consistency all texts should be black to not be racist to instinct team :)

## Screenshots (if appropriate):
Current situation with consistency (yellow is not readable):
original1

Old situation (1 week ago without consistency):
undo1

PR solution (keep consistency)
new

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change) REBASED

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by SiteEffect** [comment]
PR #1871 was merged out of consistency. I do agree, though, that it is not readable - out of consistency all team texts should be black imo.

**Comment by lluisd** [comment]
@Arengo why all texts should be black? red and blue are readable. Yellow is the unique one which is not readable, so it doesnt apply color. It's only a special case. Otherwise all texts should be black.

**Comment by Skorfius** [comment]
I like the yellow color and I can read it just fine.
Rather than changing the color straight up, why not be unique and add an arg so people can choose if they'd like to.

**Comment by lluisd** [comment]
@Skorfius lol are you kidding me?  I am an instinct member and we have several yellow gyms and everybody complains about that new color feature. Not all the people see the same color tone and that one is annoying for 75% of us, like some people dont heard the annyoing pitch noise from my fathers computer.

The person who creates the gym info slidebar puts it black for some reason and the reason was readability. Please keept it black and dont be racist to instinct with that shiny annoying yellow color.

**Comment by SiteEffect** [comment]
@lluisd I am sure you can communicate more constructively. Back to the topic, all teams black is a personal taste. Anyhow, consistency would be great - in any form and additionally making anyone happy, too.

**Comment by BrownSlaughter** [comment]
it is probably better to change the background colour so that all text is easily readable and would look better than white

**Comment by lluisd** [comment]
@BrownSlaughter this PR is only a bugfix, you are requesting for a new feature which is out of scope of the intention of my PR. I know that it will be nice to think about the best way to show it but this can be done as a feature request.

**Comment by BrownSlaughter** [comment]
The yellow text was not a bug, it was intentional to match the gym team colour in line with the others. Just because its hard to read does not make it a bug

**Comment by Buncertainc** [comment]
I would say that the yellow texts are really hard to read but I also understand that PR# 1871 was merge because of consistency.
I do agree to change all texts to black (as @Arengo mentioned) at this moment in order to take a balance between readability and consistency.

**Comment by lluisd** [comment]
@Arengo @Skorfius @BrownSlaughter @Buncertainc I've rebased and edited my PR to put all texts black and keep consistency. Also I've attached visuals of the current sitaution, old situation and the PR solution.

**Comment by lluisd** [comment]
@Obihoernchen I didn't change it to have it as a legacy but I will delete it thx

**Comment by lluisd** [comment]
@Obihoernchen done

**Comment by SiteEffect** [comment]
I like the changes while keeping consistency. Have to test it, but looks good :-)

**Comment by Obihoernchen** [comment]
It's white now ;)

You have to change:
```diff
diff --git a/static/sass/layout/_gym-details.scss b/static/sass/layout/_gym-details.scss
index d599424..6a4466b 100644
--- a/static/sass/layout/_gym-details.scss
+++ b/static/sass/layout/_gym-details.scss
@@ -12 +12 @@
-    color: _palette(accent2, fg-bold);
+    color: darken(_palette(accent2, bg), 12);
```

**Comment by lluisd** [comment]
@Obihoernchen Yes.. i missed that change I was testing it with developer tools in live. The change is done. Thanks.

**Comment by Skorfius** [comment]
Like I said no issues with yellow, and rather than make all teams suffer a plain black text make it optional. No need to change what already works, add options dont remove them...

**Comment by lluisd** [comment]
If this PR is not merged i will remove my commits by rebasing it to nothing and close it. Then i will create my own stash patch and no problem. Perhaps i am the unique or i am in the minory of instinct members that we annoy that color when we check our gyms

**Comment by nhumber** [comment]
much better

**Comment by aguita** [comment]
I agree that the instinct color needs to be fixed back to how it originally was.  It's very hard to see the details.   I am not a fan of putting black text for the other teams though.   I agree with others that please move it back to original as designed in #1422 (blue text for Mystic, Red for Valor, and Black for Instinct).

**Comment by sebastienvercammen** [comment]
Y'all sure seem to love discussing trivial things very intensely.

Yellow is unreadable, giving Instinct black (which was not how it was "designed", this was just a consistency mistake) and the rest colors makes no sense.

Merging: all teams are now equal(ly black).

**Pull request merged**
