### PR TITLE
Show Expiration Times for Pokemon, Raids, Eggs, and Lures

### PR DESCRIPTION
**Pull request by tomballgithub**
## Description

Show the expiration time for pokemon, raids, and eggs.  
Change the countdown timer labels from hour/min/sec to h/m/s in 12-hr format.

## Motivation and Context

The map currently does not show the expiration time of pokemon, raids, or eggs.
This is useful information to directly present to the user versus requiring them to do math.

## How Has This Been Tested?

This has been tested on my public map for 2 weeks
My users have been testing the feature without issues.  It is very simply.
The operating system is Ubuntu 16.04 on a VPS

## Screenshots (if appropriate):
image

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] My code follows the code style of this project.
- [X] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by sirlindqvist** [comment]
Shouldn't be 12hour format. Many people use 24h format.

Also, the format hour/min/sec was voted over h/m/s :)

**Comment by gendelbendel** [comment]
Why not leave timestamp formatting up to config? Then people can choose if they want 24hr or 12hr, defaulting to one or the other.

**Comment by tomballgithub** [comment]
I can change it to 24hr time but h/m/s/ saves space over hour/min/sec and that was one of the reasons given for the expiration time not being provided.

**Comment by sebastienvercammen** [comment]
The agreed format was indeed 24-hour `hh:mm:ss left (hh:mm)`. Even in the US military time is a thing and people should get used to better/clearer formats... *like metric, come on US...*

**Comment by tomballgithub** [comment]
Changed time to hh:mm:ss format

**Comment by sirlindqvist** [comment]
I can't get the time in () to show at all on pokemons..??

**Comment by tomballgithub** [comment]
Can you share an example? @sirlindqvist

**Comment by tomballgithub** [comment]
image

**Comment by tomballgithub** [comment]
Nice catch, fixed...

**Comment by dripdropper** [comment]
I'm not a JavaScript expert, but it looks like you're using Moment.js, which appears to support locale-based time formatting.  If so, I think this will allow the time to be displayed based on the user's OS/browser settings (e.g., 12 or 24-hour):
moment().format('LT');
IMO, this is the "correct" solution from a UX standpoint.

Edit:  Upon deeper inspection, you might have to tell Moment.js to use the user's locale via something like:
var locale = window.navigator.userLanguage || window.navigator.language;
moment.locale(locale);

**Pull request merged**
