### PR TITLE
Improve DB Schema

### PR DESCRIPTION
**Pull request by Obihoernchen**
## Description
This PR improves the current DB schema. It adds some missing indexes and changes some int columns to smallint to save some space. This should improve the performance and lower the sql cpu usage slightly.

**Please be patient, the migration can take really long!**

It adds missing indexes to the following columns:
- gym.last_scanned
- gymmember.last_scanned
- gymmember.pokemon_uid
- gympokemon.trainer_name
- pokestop.last_updated
  - included already but my DB missed it. It looks like a previous migration step missed that.
  - So let's check whether the index exists and add it
- pokestop.active_fort_modifier
- spawnpointdetectiondata.spawnpoint_id
- token.last_updated

Furthermore the following columns were changed from `int` to `smallint`, because that's more than sufficient:
```
pokemon
    pokemon_id
    individual_attack
    individual_defense
    individual_stamina
    move_1
    move_2
		
gym
    team_id
    guard_pokemon_id
	
scannedlocation
    band1
    band2
    band3
    band4
    band5
    midpoint
    width
				
spawnpoint
    latest_seen
    earliest_unseen

spawnpointdetectiondata
    tth_secs

versions
    val

gympokemon
    pokemon_id
    cp
    num_upgrades
    move_1
    move_2
    stamina
    stamina_max
    iv_defense
    iv_stamina
    iv_attack
			
trainer
    team
    level
```

## Motivation and Context
missing indexes are bad and I saw that int is unnecessary

## How Has This Been Tested?
test map with mysql and sqlite
and my map

## Screenshots
I added an additional message because this DB schema upgrade can take some time:
```
[      MainThread][        models][    INFO] Detected database version 15, updating to 16...
[      MainThread][        models][    INFO] This DB schema update can take some time. Please be patient.
```

## Types of changes
- [X] Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [X] My code follows the code style of this project.

### CODE REVIEW

**Comment by mpw1337** [comment]
> pokestop.last_updated
included already but my DB missed it (very old DB, maybe missed in previous migration steps)?
If you have an older DB can you check whether you have this index in your DB please?

My db doesn't have this index either.
image

**Comment by Obihoernchen** [comment]
@mpw1337 thank you for your report! I included a simple check to add this index if it's missing.

**Comment by jangrewe** [comment]
Ah, indexes! My DB server is churning quite a bit, mostly because of other stuff creating quite a bit of DB IO, so i'm very looking forward to this.

**Comment by 3my** [comment]
Hey I am a bit late to this but I am just wondering if it would be a good idea to conditionally add the index i.e. if index does not exist then create? Additionally it would be good if there was some output to the console to notify of update completing.

Thanks for the time you guys put into this btw you guys are awesome

**Comment by Obihoernchen** [comment]
For a status report during the upgrade run the following mysql command: `show processlist;`
The index addition isn't the big part here. Modifying the column types takes a lot of time though.

**Pull request merged**
