### PR TITLE
fix duplicate pokemons in gym label and sidebar

### PR DESCRIPTION
**Pull request by dev042**
fixed duplicate in gym label and sidebar

## Description
This PR fix the duplicate pokemons in gym label and sidebar

## Motivation and Context
Saw today in my Map duplicate pokemons in the gym sidebar.
Search on know issue and saw https://github.com/RocketMap/RocketMap/issues/1683 and it fix also the duplicate in Gym label

## How Has This Been Tested?
Tested on my Map and with curl.

## Screenshots (if appropriate):
before:
duplicate_gym

after fix:
duplicate_gym_fix

## Types of changes

- [ x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by SiteEffect** [comment]
A ``distict`` call might also fix the multiple Pokémon in Gym-Info windows. A lot of users ask in #help of Discord recently about this bug and there was none fit for all solution to it.

**Comment by dev042** [comment]
@Arengo i don't have this bevavoir, but will take a look at the source and fix it too.

**Comment by SiteEffect** [comment]
I had it month ago, but grunt build fixed it and deleting out of table, due to code modifications. But this doesn't fix for others, they had fresh clones.

**Comment by dev042** [comment]
@Arengo yes, this fix also the duplicate in Gym Label. Updated Title etc.

**Pull request merged**
