### PR TITLE
Check if check_challenge exists before setting captcha_url/send download_settings with every request

### PR DESCRIPTION
**Pull request by FrostTheFox**
~~According to niico, check_challenge is GONE~~ (EDIT: It's back in the latest version), and download_settings is sent with every request "except the first getplayer".
## Description

I have no idea what further needs to be changed, if anything, but this should send download_settings with the majority of the requests, since a whole lot of everything seems to call apiRequests.py, which eventually loops everything through send_generic_request (as far as I can tell, once again, I could be missing things, please change or let me know if I am.)
## Motivation and Context

This was changed, and it needs to be reflected in our requests.
## How Has This Been Tested?

Not tested, as always, please fully test. Passes flake8 locally.
## Screenshots (if appropriate):
n/a
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by FrostTheFox** [comment]
Once again, I'm not very experienced in the api request portion of the code, but I *think* those need commented out, because wouldn't they complain as the check_challenge part of the response is now gone? The only thing I can think of is if some weird protobuf nonsense makes it still have an empty key there.

Please let me know if I'm wrong about any of this or if more needs done, I just wanted to get the ball rolling because no one else has opened a PR on this subject and it needs done.

(so it is known, my intention was to simply cut off anything that called or relied upon check_challenge to start, so that we block entry points for the captcha code, and then we can think long-term about what to do with the leftovers.)

**Comment by friscoMad** [comment]
There is a missed check in models.py in the encounter handling.
Anyway as said in Discord I would prefere to switch to a construct like this one: 
https://github.com/RocketMap/RocketMap/blob/9a5a1fdaf776de7c1be199a429284094320d6629/pogom/captcha.py#L183

This way we will leave the feature there and we can clean up everything if we remove all captcha handling later on.

**Comment by FrostTheFox** [comment]
Holding pending more info on reports check_challenge is back in 0.85.1

**Comment by Alderon86** [comment]
for now, it improved the lifetime of my accounts, but lets see how this check_challange thing goes

**Comment by FrostTheFox** [comment]
Since the next API version is likely to be forced soon and check_challenge is back in that one, I'm hesitant to remove req.check_challenge right now.

I'll leave the download_settings fix and the ifs, because that makes things cleaner if we do need to remove check_challenge again (which could definitely happen because niantic is weird).

**Pull request merged**
