### PR TITLE
Fix empty queue issue + set timeout for all requests

### PR DESCRIPTION
**Pull request by Obihoernchen**
## Description
This PR adds a 5s timeout to the API version check to fix the empty queue issue.
In some rare cases with some bad proxies the API version check might hang there forever and blocks all search queue updates. Therefore after some time the queue runs out of items and your instance stops scanning.

Furthermore it adds a 5s to all GET and POST requests.

## Motivation and Context
running without a version check wasn't the best solution for me ;)

## How Has This Been Tested?
my map + a map from another discord user

## Types of changes
- [X] Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [X] My code follows the code style of this project.

### CODE REVIEW

**Comment by Obihoernchen** [comment]
@sebastienvercammen yep good idea. Will do so!

**Comment by Sk00DaT** [comment]
im experiencing this issue as well added the timeout but issue still persists :( hopefully when you add the other timeouts it fixes the problem

**Comment by Obihoernchen** [comment]
@sebastienvercammen done. I've added 5s to all requests I found. 5s is default proxy timeout as well.

**Comment by sebastienvercammen** [comment]
@Obihoernchen Ah. Perhaps it makes more sense to use `args.proxy_timeout` for the request timeouts as well, instead of a hardcoded `5` seconds?

**Comment by sebastienvercammen** [comment]
RE Discord: We'll leave it at 5s for now. Proxy timeout would be confusing when someone isn't using proxies.

**Pull request merged**
