### PR TITLE
Allow more than three fields in account csv file and minor text changes.

### PR DESCRIPTION
**Pull request by weizh888**
## Description

- Allow to use the csv account file with more than three fields.
- Some minor text revisions.

## Motivation and Context

Sometimes the csv file could have four fields:
>service, username, password, level

especially in the generated file when using the PoGoAccountCheck to check the accounts.

The code still tries to read the first three fields, but just ignores further fields, which is same as that for high-level-accounts.

## How Has This Been Tested?

Tested on my own Map.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by Alderon86** [comment]
I dont want to dissapoint you, but this is already included in #2376 (not pushed yet, but locally working)

**Comment by weizh888** [comment]
@Alderon86 That's fine, then hope #2376 is merged soon.

**Comment by sebastienvercammen** [comment]
@Alderon86 @weizh888 We'll keep this PR open, it's minor and can be merged before #2376.

@weizh888 Travis is complaining, can you push a fix?

**Comment by weizh888** [comment]
@sebastienvercammen Just revised to make it pass the check.

**Pull request merged**
