### PR TITLE
make hash-key a requirement

### PR DESCRIPTION
**Pull request by h0us3cat**
## Description
Make hash-key a requirement.

## Motivation and Context
It fixes scrubs asking why their map is not working.

## How Has This Been Tested?
/

## Screenshots (if appropriate):
/

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Comment by jagauthier** [comment]
This makes sense to me. I considered it as well.

**Comment by Obihoernchen** [comment]
Nope sorry. There is -os as well. hash-key isn't required!

**Comment by SiteEffect** [comment]
That's of no use, where and how you placed it. However, in ``runserver.py`` there might be use under 
```python
if not args.only_server:
    if not args.hash_key:
        log.error("Hashkey is required for scanning. Aborting.")
        sys.exit()
```

**Comment by FrostTheFox** [comment]
good idea, implemented as @Arengo has it :)

**Pull request closed without merging**
