### PR TITLE
Colorify logs

### PR DESCRIPTION
**Pull request by springjools**
## Description
Add different colours to different log level messages. As now: these are the colours:
        'DEBUG':    'blue',
        'INFO':     'white',
        'WARNING':  'yellow',
        'ERROR':    'red',
        'CRITICAL': 'red,bg_white',

## Motivation and Context
To filter out spam easier

## How Has This Been Tested?
Tested on local machine.

For some reason my environment produces grey text as normal INFo text, and bold white as the WARNING level. I believe this is only something in my local environment, and I kind of accepted how it looks so I stopped bothering to find out the cause.

It's using this package: https://github.com/borntyping/python-colorlog

Compatibility: colorlog works on Python 2.6 and above, including Python 3.

On Windows, requires colorama to work properly. A dependancy on colorama is included as an optional package dependancy - depending on colorlog[windows] instead of colorlog will ensure it is included when installing.

## Screenshots (if appropriate):
http://prntscr.com/djb4ud

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by springjools** [comment]
image

**Comment by Arengo** [comment]
Very nice addition. Info and warning colours could be a bit different as default I think. I changed mine to Info-lightblue, warning-orange.

**Comment by springjools** [comment]
Did you find a way to add own colour definitions? I tried to investigate but only found those default colour names as mentioned in the package readme.

**Comment by sebastienvercammen** [comment]
Can't merge: breaks compatibility with Windows because it would require additional software to be installed just for colors in logs.

**Pull request closed without merging**
