### PR TITLE
Variable size of gyms depending on level

### PR DESCRIPTION
**Pull request by springjools**
Variable size of gym shields depending on gym level:
1 to 5: 32 px
6 to 7: 40 px
8 to 9: 48 px
10: 56 px

## Description
Variable size of gyms depending on level

## Motivation and Context
Makes improvement to map

## How Has This Been Tested?
Tested on fork, ran npm run build and tested the map, it works
http://prntscr.com/detzh1

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by springjools** [comment]
34be70e1aafe4314b1b8a361852dad59

**Comment by ashleykleynhans** [comment]
I prefer it the way it is at the moment. I don't think this is an improvement, it makes things worse.

**Comment by gabaod** [comment]
is there a way you can put in a option on map that allows values 1-10, if 1 show all gyms, if 2 show gyms lvl 2+, if 10 show gyms 10+     That I think would be much more useful.. Ive attempted myself. I can get it to display just lvl 10 gyms, but after 5-10 seconds the map auto refreshes and all the rest of the gyms populate from somewhere, couldnt figure out what class was causing that.

**Comment by jabberjabber** [comment]
@gabaod check out https://github.com/PokemonGoMap/PokemonGo-Map/pull/1288

**Comment by ashleykleynhans** [comment]
#1288 is a more useful change than this one in my opinion.

**Comment by gabaod** [comment]
oh wow.. lifesaver guys. never knew how to view closed prs ;)   Got that installed and its working nice.  did notice its very odd changing the settings as its making its first scan, but refreshing page the settings work perfectly and all new updates match them

**Comment by springjools** [comment]
What's the point of comparing this to pr:s that are not related?

**Comment by ashleykleynhans** [comment]
#1288 is related, it provides a filter, this PR breaks the map it doesn't make it better.

**Comment by springjools** [comment]
Please discuss #1288 on its page and here only this pr. Thank you!

**Comment by ashleykleynhans** [comment]
@springjools don't be a moron, I am discussing your PR and telling you thats its stupid.

**Comment by springjools** [comment]
You need to provide more details to be constructive.

**Comment by gabaod** [comment]
I also agree. This doesnt help benefit the map in any way.  I will revive 1288 and keep it part of my test branch with 1501.  There is no need to take comments personally.  The point of this system is to submit code that we may feel is a good solution for the project, and its up to the users to notify the devs if they like the PR and if it should be merged or not.

**Comment by springjools** [comment]
Absolutely, of course you can disagree with this pr, just say what it is you are disagreeing with? If you could say why it doesn't benefit the map.

**Comment by simonbuehler** [comment]
while i see the effort you put in i also find it visually distracting to have different size icons

**Comment by springjools** [comment]
Closing this due to lack of interest.

**Comment by sebastienvercammen** [comment]
Feedback from the community (both on Github & the feature requests platform) shows this isn't currently something that people want.

But thank you for the contribution.

**Pull request closed without merging**
