### PR TITLE
[Redirected] Re-add lured Pokestop support and adjust current active lure times (Valentine's event)

### PR DESCRIPTION
**Pull request by Arengo**
## Description

Adjusts the timers of lured Pokéstops during the Valentine's event and retrieves ``lure_info`` data to display active lured Pokémon on map.

## Motivation and Context

The current lure timers are now 6 hours during the Valentine's event. Sadly, this is not reflected by maps which only show 30 min before completely wiping the lure animation for 5:30 minutes until ``last_modified``changes again. This is wrong displaying at the moment and should be adjusted at least for the duration of the event. Now, this is soft-coded! FortDetails, accessible when gym-info is enabled, provides the correct lure expiration time.

Additionally, the feature of active lured Pokémon was dumped for, at least for me, unknown reasons. Hence, this is being re-implemented but is not finished yet. It features a toggle ``-lp``, ``--lured-pokemon`` and of course should be shown on the map which is currently WIP.

## How Has This Been Tested?

On my local machine. Correct event timers are working as expected.
Keep in mind that Pokéstops have to be scanned closed enough to retrieve actual ``lure_info`` for the lured Pokémon - 450m radius is not sufficient! Additionally the display of Pokémons is not finished, yet.

## Types of changes

- [x] Temporary event fix
- [x] Re-implementation of feature to new code base

## Checklist:

- [x] My code follows the code style of this project. (Pep8 & Travis has still to be checked)
- [x] My change requires a change to the documentation. (Flag has to be shown in documentation, still to-do)
- [ ] I have updated the documentation accordingly. (See above.)

### CODE REVIEW

**Comment by sebastienvercammen** [comment]
Valentine's day is nearly over, and this PR is not good enough to be re-used for the future. A long-term implementation without hardcoded values could have been merged, perhaps something to take about later on.

**Comment by SiteEffect** [comment]
I stopped working on it for the last two days. You are right in your statement. Might look after a soft-coded implementation for the future.
For further lure support please head over to @onilton PR #1633 "New lured pokemon support"

**Comment by sebastienvercammen** [comment]
Reopened at author's request for Github/Travis learning/testing.

**Comment by SiteEffect** [comment]
This PR now contains a soft-coded lure duration implementation, but an additional API call is needed which also counts towards RPM if using hashing service. For manual set lure duration please refer to PR #1824 (Custom lure duration by @onilton )

**Comment by SiteEffect** [comment]
I DID IT!

**Comment by SiteEffect** [comment]
This PR contains code to receive ``FORT_DETAILS`` and might have snippets to re-use.

**Pull request closed without merging**
