### PR TITLE
Fix captcha webhooks and captcha protobuf

### PR DESCRIPTION
**Pull request by friscoMad**
## Description
Adds the wh-type captcha as I forgot captcha wh existed and fixes access to success in captcha requests.

## Motivation and Context
Give captcha some love.

## How Has This Been Tested?

Tested that it works without captcha handling enabled, without WH, with WH using 2captcha and manual.

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] My code follows the code style of this project.
- [X] My change requires a change to the documentation.
- [X] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by friscoMad** [comment]
Rebased and fixed some calls that were using the old system.
Tested with 2captcha and manual and it works.

**Comment by sebastienvercammen** [comment]
@friscoMad Conflicts because of the doc updates, can you rebase?

**Comment by pogo-excalibur** [comment]
In addition to the docs rebase, would you mind updating the section in webhooks.md regarding `captcha` events being sent regardless of `wh-types`?

(As this PR fixes that)

**Comment by friscoMad** [comment]
@sebastienvercammen @pogo-excalibur rebased and updated docs

**Pull request merged**
