### PR TITLE
[On Hold] Unown forms

### PR DESCRIPTION
**Pull request by pogo-excalibur**
## Description
This PR adds icons and spritesheets for the 28 unown forms, and modifies `map.js` and `statistics.js` to use form-specific sprites/icons where possible.

## Motivation and Context
This PR started as an attempt to view unown icons in gyms. After the release of 0.77.1 this was expanded as it now seems likely that some Gen3 Pokemon will also have alternate forms.

## How Has This Been Tested?

* Gym sprites have been tested using live data (courtesy of the European unown events).
* Wild pokemon icons/sprites have been tested using mocked data

## Screenshots (if appropriate):
Unown in a gym:
unown_letter

Unown in the wild:
unown_letter_2

## Types of changes

- [X] New feature (non-breaking change which adds functionality)

## Checklist:

- [X] My code follows the code style of this project.

### CODE REVIEW

**Comment by sirlindqvist** [comment]
Funny I was about to open a pr like this tonite ..

**Comment by SkOODaT** [comment]
this doesn't fully work ... you need to add ......`

> 'form': pokemon.pokemon_display.form

` to gym_pokemon[i] in phrase_gyms....

**Comment by pogo-excalibur** [comment]
Indeed I do. In fact, that's arguably the most important line.

**Comment by SkOODaT** [comment]
> +    if (id === 201 && form > 0) {
> +        return `static/icons/${id}-${form}.png`
> +    }

Might not be a good idea its trying to find the unowns by number ... ie 201-12.png might want to use the const unownForm in map.js to change it to a letter ...... ie 201L.png 

> + return `static/sprites/${id}${unownForm[`${form}`]}.png

more users will more then likely have sprite pngs labeled like that, the other way is confizzleing :)

**Comment by pogo-excalibur** [comment]
@SkOODaT I took the index-based approach in order to handle the `?` character without an ugly workaround.

(In Windows, `?` is not permitted in a filename.)

**Comment by pogo-excalibur** [comment]
!! This PR is currently on hold until an updated mechanism for spritesheet generation is merged. !!

**Comment by pogo-excalibur** [comment]
**!! This PR is currently on hold until an updated mechanism for spritesheet generation is merged. !!**

**Comment by billyjbryant** [comment]
#2461 handled this PRs changes and sprites are being handled by #2348 @pogo-excalibur is this good to close?

**Comment by pogo-excalibur** [comment]
@billyjbryant Yes 👍

**Pull request closed without merging**
