### PR TITLE
Choose map service provider for navigation

### PR DESCRIPTION
**Pull request by sirlindqvist**
Option to be able to choose Apple Maps for navigation instead of default Google Maps.

## Motivation and Context
Created for iOS users having trouble with the Google Maps app.

When clicking a coordinate link a new window opens in Safari and asks for using the Google Maps app.

ios_google_maps

If taping 'use the app' the Apple AppStore opens even if the app already is on the phone. From there it's possible to click 'Open' and the Google Maps app loads, however it's not possible to start navigation. If taping 'no thanks' the question loops over and over again. 

Selecting Apple Maps instead as map service provider opens the native iOS maps app without any trouble at all.

options

## How Has This Been Tested?
On my own map. Sucessfully tested on both iOS 10.10.3 (iPhone 6S) and MacOS High Sierra public beta 7 (iMac mid 2011).

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by sebastienvercammen** [comment]
To be discussed if "map service provider" should be an option, or detected via browser fingerprinting.

**Comment by sirlindqvist** [comment]
I know you would ask that @sebastienvercammen :)

**Comment by sirlindqvist** [comment]
Got fingerprinting working with client.js if we decide to go for this.

**Comment by sebastienvercammen** [comment]
@sirlindqvist We're keeping it as is instead of browser fingerprinting so iOS users still have the option to install and use Google Maps on iOS.

**Comment by sirlindqvist** [comment]
OK! I'll check the code and will do some small adjustments. Now, a new tab is opened in browser when Apple Maps is being used and the app opens on phone, shouldn't do that :)

**Comment by friscoMad** [comment]
@sirlindqvist still need to do some fixes or is the PR good as it is now?

**Comment by sirlindqvist** [comment]
Will fix the new tab issue

**Comment by sirlindqvist** [comment]
@sebastienvercammen and @friscoMad this is ready for review.

**Pull request merged**
