### PR TITLE
Remove Trainer table and old db migration from RocketMap.

### PR DESCRIPTION
**Pull request by Alderon86**
## Description

Removed Trainer Name and Level from Gym-Info.
## Motivation and Context

 - Per the EUGDPR, these usernames can be (and have been) cross-referenced with Google and other social media to identify the real-life person behind the username. Collection and storage of this information can be illegal unless you've been given explicit permission from the user whose data you're storing, it's opt-in, you store it according to the required guidelines, and so on. In short: none of the RocketMap websites comply with any of these things. Before you say "but I don't live in the EU I can do whatever I want": no, that's not how international law works, your user is still in the EU and still has his/her rights.

- Editing RocketMap or setting up an external script to track people's real-life habits is extremely trivial in its current state. We've looked at all options, and setting up an automated "people tracker" to track people's work/school habits, coffee places, favorite locations, ... is very, very simple to do. The recorded data and the high frequency at which people log into Pokémon Go make the consequences of this even worse.

- What makes this more problematic, is that the above point can be used to identify (read: approximate) the person's age group. This means it's possible to intentionally separate children from adults. I don't think I need to continue this train of thought for everyone to understand.

- Several live implementations of this stalking behavior had already been implemented. Some users via websites, others via Discord bots or other tools that allow you to track a certain person without their consent or knowledge.

 - In response to our decision, we've received some immensely negative feedback from a handful (tiny minority) of users. Rather than push us away from the decision, it reinforced it. None of you should be deciding about the security and privacy of others (including my own) - that's the individual's job, and we're restoring their ability to do so. (Note: and we've received a whole lot more positive responses. Big thanks to all of these people who understand us.)

- Old database migration got removed to avoid any workarounds.

## How Has This Been Tested?

locally 
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the code style of this project.
- [x] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by daangroot** [comment]
Did niantic knock on the door? It's sad to see this feature being removed.

**Comment by Alderon86** [comment]
@daangroot we want to make RocketMap more "legal", so this feature needs to go.

**Comment by urinella** [comment]
And to make this configurable is no option?
In my opinion every RM hoster should be able to decide by himself/herself which information he/she wants to display on his/her map and not the hoster of the repo. Also by his/her own risk.
This PR would remove one of the main reasons why people are using RM as map -> The beautiful display of data about trainers and their Pokemon.
This also could cause that RM will be splitted in many different forks and a lot of users could leave the main project.

Just a suggestion and thoughts from a first-day user.

**Comment by farstarss** [comment]
@Alderon86 to make RM legal regarding the TOS of TPC and NIA it would be necessary to remove scans of any kind and all information gathered from the pgoapi as well well. Shell we go for it? :P

The only reason I might agree with are privacy concerns. And that should be up to the map hoster / local community as different cultures have different thoughts about privacy.

**Comment by Alderon86** [comment]
@farstarss @urinella this was decided by the rm dev team, we had many discussion about that on discord.
@sebastienvercammen can agree on this.

**Comment by FrostTheFox** [comment]
To clarify a bit further:
The legal implications are just a sort of "also why we should get rid of this". Trainer name could be considered to be PII in some areas. No, Niantic did not contact us, nor did any other organization, otherwise we wouldn't open a PR, we'd have directly committed this to the repository.

The main reason why we are removing trainer names is for privacy and safety reasons. Not too long ago, we were privy to a screenshot of a Discord bot, which, on command would return the latest gyms a player had been to, the pokemon they put in that gym, **and the dates and times in which they visited that gym**. This is just creepy and weird, and the fact that they even called the bot "Stalker", with the command being ".stalk" makes it even worse.

We've also gotten people saying things similar to: `Someone I know got a text message from someone in his region. The guy had been tracking him and could tell when he was at work or not. He sent him a message to ask if he shouldn't be at work when he took over a gym during working hours.`

It really made us realize that with the trainer info being collected by RM, it would make it very easy for anyone who wanted to to stalk on others as they moved from gym to gym, *without even leaving their home*. They could even develop an interface which would let them view the common paths of a trainer. *Tell me it's a conspiracy theory and that no one would really do that*, but considering that "Stalker" Discord bot and the numerous reports of people watching other's locations, I have no doubts.

We've decided that the benefits of having trainer information in RM does not outweigh the costs. "Leaderboards" (which simply are there to inflate ego), "people like information", or "taking down certain people in gyms" are not reasons which we consider to be above protecting others (and remember, there are children which play this game) from potentially being stalked, physically harmed, kidnapped, whatever it may be.

You can say "forks will just add it" as much as you want. It's about taking a stand and making it harder for bad actors to do these things. If you want to disrespect the privacy and safety of others, that's up to you, but we're not going to stand back and leave it in our program for someone to just enable.

RocketMap is a tool for tracking Pokemon. It's not meant to track people.

**Comment by sebastienvercammen** [comment]
☝️ Correct, this is a RocketMap team decision after a lengthy discussion.

* Per the EUGDPR, these usernames can be (and have been) cross-referenced with Google and other social media to identify the real-life person behind the username. Collection and storage of this information can be **illegal** unless you've been given explicit permission from the user whose data you're storing, it's opt-in, you store it according to the required guidelines, and so on. In short: none of the RocketMap websites comply with any of these things. Before you say *"but I don't live in the EU I can do whatever I want"*: no, that's not how international law works, your user is still in the EU and still has his/her rights.
* Editing RocketMap or setting up an external script to track people's real-life habits is **extremely trivial** in its current state. We've looked at all options, and setting up an automated *"people tracker"* to track people's work/school habits, coffee places, favorite locations, ... is very, very simple to do. The recorded data and the high frequency at which people log into Pokémon Go make the consequences of this even worse.
* What makes this more problematic, is that the above point can be used to identify (read: approximate) the person's age group. This means it's possible to intentionally separate children from adults. I don't think I need to continue this train of thought for everyone to understand.
* Several live implementations of this stalking behavior had already been implemented. Some users via websites, others via Discord bots or other tools that allow you to track a certain person without their consent or knowledge.
* In response to our decision, we've received some immensely negative feedback from a handful (tiny minority) of users. Rather than push us away from the decision, it reinforced it. None of you should be deciding about the security and privacy of others (including my own) - that's the individual's job, and we're restoring their ability to do so. *(Note: and we've received a whole lot more positive responses. Big thanks to all of these people who understand us.)*

Although we usually invite people to join in the discussion and share their perspectives, this is an exceptional case and **this PR is not a discussion.** It's a RocketMap decision.

We recommend that anyone who feels that they need to persist in their vocal/outspoken disagreement with this decision, should uninstall the Pokémon Go application, move away from their smartphones, and take a long, hard second look at themselves and their actions.

Nothing in Pokémon Go (or any other application/technology) is worth sacrificing **other people's** privacy and security for the sake of *"entertainment"* or *"a feature"*.

**Comment by daangroot** [comment]
What about only removing the time a pokemon was placed in a gym? This way "stalkers" only know people have visited a gym not when.

**Comment by pogo-excalibur** [comment]
Knowing which gyms people are visiting still provides a lot of data about each trainer, and doesn't solve any of the issues that @sebastienvercammen just mentioned.

**Comment by daangroot** [comment]
And I don't know if the RM team knows, but in the game you can see the deployment time as well. Please rediscuss this with the team, I think it's way too drastic.

**Comment by FrostTheFox** [comment]
No. It's not up for rediscussion. The game doesn't let you view info from any gym you want from home.

**Comment by 123FLO321** [comment]
~~@FrostTheFox While this is a real problem it's not a problem for everyone. 
While larger maps should turn off trainer names, small maps with restricted access to a handful of people probably don't need to do so.~~

~~If one wants to stalk someone in a small area they could do this with the Pokemon Go app alone. It's not hard to find a players "Home" or "Work" gym/pokestop if you're an active Pokemon Go player. And in this case RocketMap would not give them any information they wouldn't know otherwise.
In small areas most players know each other because of raids anyways.~~

~~I totally get why such an action is needed, but I would love an opt-in option for trainer-names for small maps.~~

Edit: Wrote this before @sebastienvercammen commented.

**Comment by Goldclownfish** [comment]
We've also gotten people saying things similar to: Someone I know got a text message from someone in his region. The guy had been tracking him and could tell when he was at work or not. He sent him a message to ask if he shouldn't be at work when he took over a gym during working hours.



That is clearly someone who gives their number out to anyone or has publicly posted their phone number.  So a handful of individuals acting like idiots are going to cause map users to lose the ability to place their mon in a gym an be able to get the iv from it. I’m completely against entirely removing this. Maybe u all should come to my town an watch the real life stalker I have drive by the gyms while I’m taking them from him. Most of us do not run a stalker bot an just because one idiot has done so it should not penalize the rest of the map admins an users from having a useful feature.  The team should spend some time going after the maps that clearly are earning the map host an income instead of removing a feature that small town maps enjoy an like. If we are going to the extent that we have to remove features to protect an individual or handful of them that are not  smart enough to not hand out or publicly display their phone number then maybe iv’s should also be removed so that map users don’t have an advantage over legit players.

**Comment by FrostTheFox** [comment]
`So a handful of individuals acting like idiots are going to cause map users to lose the ability to place their mon in a gym an be able to get the iv from it.`

You'll still be able to do this, the deployment time and IV/CP is still there, we're just removing the connection to trainer info. You should be able to know what's yours, but not so much others.

**Comment by apemsel** [comment]
Sad to see this go without a config option, will have to fork in that case since players here love the high score table.
One way to fix this would be to make it opt-in per trainer?
I do see the privacy implications, but we are a very rural area where every trainers knows each other anyway, our map is behind login and of course we do already remove trainers on request (we have not received one so far)

**Comment by urinella** [comment]
@sebastienvercammen 

> **this PR is not a discussion**

This really shows where the RM train goes. So many good PRs but no merges for month. (For example the weather PR was merged after two month, the other one with the map part is dead now because no merges.) And the last stop of the train will be a project without any people doing anything.

Calling this open source? Open source is not discussing in your private PR-channel where only a few, selected people have access. Open source discussing is this what we are doing here.


And the points you are mentioning are unique exceptions. 1000 maps over the world and 2 stalkers -> Remove trainer names? This can't be the reason seriously.

So removing Trainer-names is preventing stalking? No it isn't. The people who want to stalk can do it. It's so simple to free-load an App like PokeTrack from the Playstore. So stalkers have access again or stalker can follow people in real life without the map....

Man, I play a gps-based online game. Of cause my data is stored somewhere and can be abused. Do you know Ingress? Niantic is putting the playernames and times on their own map. (Okay you have to agree in TOS about this and in Pokemon not)
People should know that and it's not the fault of a city-scanner that people get stalked.
Or is it the fault of a park owner that somebody was robbed, raped or killed inside his park? I don't think so.

Or have we now to close every bank in the world because they could get robbed?
Or closing every ice cream store because kids can get diabetes from it?


I really can't understand that "the RM team" think they have to decide for other people.
And this one is going in the really wrong direction! This is not open-source anymore. No good updates. Merging after months. Kicking good people. Go on and you'll losing more and more good people making PRs.

**This is not open source. This is prison.**

**Comment by sebastienvercammen** [comment]
@urinella I see that you don't understand our reasoning, that's unfortunate.

I will address a handful of your comments and I'm willing to discuss a few to clarify them, but you're clear that you have a very aggressive attitude towards all of this, including towards the RocketMap team without even knowing us! So take a handle on your attitude.

> So many good PRs but no merges for month

Per [our commits](https://github.com/RocketMap/RocketMap/commits/develop), 25 commits in this month alone (today being the 13th day).

> For example the weather PR was merged after two month

Yes, and you'll notice that there were still changes to the PR in the last handful of days. RocketMap stands for organization and code quality. We don't merge code that isn't ready, we actually manage our repository.

Last changes, made by myself, 12 days ago, with the author missing in action. Merged the same day.

We also always wait a certain amount of time when requesting changes to give authors the chance to maintain their own work. Life happens and not everyone has time to contribute every day.

We understand people want things merged *fast*, but it's more important to us to let people live their lives first. Pokémon Go isn't remotely important enough not to.

> Open source is not discussing in your private PR-channel where only a few, selected people have access

The #pr Discord channel is open to anyone who has contributed in RocketMap's PRs. We also have a #reviewers channel that doesn't have a PR requirement. Lots of people in those channels, and none were "selected", they just contributed and asked to join.

> And the points you are mentioning are unique exceptions. 1000 maps over the world and 2 stalkers -> Remove trainer names? This can't be the reason seriously.

**Point one:** I know of just 3 maps who, combined, have over 100 million visits per month. Forget "1000 maps", let's take 3 for now. 100 million visits - I've seen the visitor data, so if we approximate it we get ~5 million visitors.

The scope of this data is **immense**.

"2 stalkers"... You're only talking about the two people we've mentioned from our personal, direct group of contacts. We have more, and we know (and can approximate that) there are many, many more.

**Point two:** Let's say the world is beautiful and stalking doesn't exist. Collecting and storing this data still removes people's privacy and security, **and** is illegal. We would still remove it. It doesn't take an active stalker for it to be illegal.

> Man, I play a gps-based online game. Of cause my data is stored somewhere and can be abused

You might know something, but don't assume that everyone in the world does. [The concept of the ten thousand](https://xkcd.com/1053/). Pokémon Go is a game with a *very* broad reach, and we should be aware of, acknowledge and respect whose data we're using.

> It's so simple to free-load an App like PokeTrack from the Playstore

RocketMap can only be responsible for its own project. The difference with RocketMap *also* having stalking features, is that by removing them we're not **enabling** anyone to continue toxic, aggressive and invasive behavior.

And we send a clear message: RocketMap is about everyone, we're not about the tiny, tiny minority that gets irrationally angry over a feature being removed for good reason who think they're much bigger than they are.

> Kicking good people. Go on and you'll losing more and more good people making PRs.

We have [many contributors](https://github.com/RocketMap/RocketMap/graphs/contributors), some who have stayed with us for over a year (and Foxbabe and myself being around from the very start, so ~2 years).

Open source includes the coming and going of hundreds (or thousands) of contributors, but RocketMap will not degrade its values for any one person. Especially not [one who has never built any contributions to open source](https://github.com/urinella?tab=overview).

> I really can't understand that "the RM team" think they have to decide for other people. This is not open source. This is prison.

Today, you've learned the difference between organization and open source. We have an open source, but we also manage it, with our own values.

And our values are telling us to remove this feature, which not only fuels toxic and invasive behaviors (witchhunting, stalking), but which is also **illegal**.

This is immensely common. All maintainers have their values.

**Comment by farstarss** [comment]
Ok, I get that you are not willing to not merge this PR but let me propose a new way to solve the privacy issue:

Instead of offering an opt-in _for the hoster_ (which you clearly don't want) I suggest to offer an opt-in _for the user_ per map. 

One way I could think of to do so is by requiring a TSR travelers card (https://thesilphroad.com/card) and ask the user to set their total xp to a random number. Sadly there is no option (like OAuth 2.0) to allow a user to authenticate with his / her travelers card yet.
Since the travelers card requires users to authenticate against others in person and with their in game name there is very little chance for abuse here. 
In other words: A trainers name on TSRs card is equal to his/her in game name.

You can read more about TSRs travelers card here: https://thesilphroad.com/news/pokemon-go-player-network-travelers-cards-silph-league/

If you are willing to agree on such an opt-in option _for users_ I assume this could all come to a point where everyone is (more or less) happy as RM can no longer be held responsible for infringing privacy regulations as it's the users own choice to allow his / her data to be used / published by a certain map.
Of course there has to be some kind of statement that the users has to agree to in addition to linking their travelers card.

**Hopefully this now _is_ up for rediscussion** and you can hold on with merging this PR without considering every option. 

Another option I can think of would be to ask a user to place a pokemon into a gym with a certain amount of cp that RM _has not seen yet_ to avoid spoofing such information (i.e. someone could falsify the opt-in if he / she knows which pokemon a trainer usually puts into gyms).

I'm a little surprised that no one suggested any of this yet.

**Comment by dongemus** [comment]
I am just chiming in because the people speaking up are the opposition.
I cannot wait for the automated witch hunt/stalking feature to be removed
officially. We have had several problems with this in my area. I don't
think people can appreciate the harm done until it happens to someone they
care about.

I removed mine with CSS months ago but it leaves the sidebar kind of broken.

Lastly, even though the devs clearly stated here that this was final and
not up for discussion, they have been very patient to still try to clear
things up and that is appreciated.

**Comment by sebastienvercammen** [comment]
@farstarss 

> I'm a little surprised that no one suggested any of this yet.

We have (though not with TSR). It's similar to @apemsel's question just above.

In short: the removal of this data in its current form is not a discussion, but adding a feature that allows individual trainers to opt into a new feature (whether that's trainer data storage in general or specifically a leaderboard remains to be discussed) *is* open for discussion.

Our thinking is two-fold:

1. This data, in its current form, must be removed from RocketMap. No delaying.
2. Discussion of new features will take time, especially if it re-implements any form of trainer data storage since we'll have to cover all risks and downsides.

In order not to delay the removal of sensitive information, the merge of this PR won't be tied to how fast we can come up with (and test) a solution everyone agrees is reasonable.

We'll remove the data first and fix all of the problems that it caused, and we'll have time and freedom as much as we want afterward to discuss all possibilities at great length (for which I hope you'll join us [on our Discord](https://discord.gg/rocketmap)).

Removing the data also removes all PII data from production servers and lets us start with a clean slate for new features.

Implementing TSR is interesting, though Silk Road has always been explicitly against mappers - until they released a Discord network with a bot that gives them data on every single Discord that joins the network, which is another problem in itself.

Maybe there's an opportunity here to implement something that builds a community between mappers, without exposing everyone's domains or Discords, that does support OAuth and that has verifiable opt-in per individual?

All things we'd like to talk about (and that we've been talking about on Discord), but the removal of this data right now is happening *(and would need to happen anyway for any opt-in feature we choose to build)*. We focused on making that point clear in our communication, but I'm glad you asked your question so we could clarify.

About community features that use this trainer data: I'm sure we can come up with a handful of features that don't encourage negative behavior and that prevent users from witch-hunting *(e.g. being mad at people because you feel they capture gyms too fast so they get called cheater/spoofer and they eventually get excluded from social events -- until it turns out the person just enjoys jogging)*.

**Comment by 123FLO321** [comment]
Would it be possible to keep the trainers table but use the trainers-id instead of their name?
This way 3th party tools like Worldopole can still collect stats about level distribution without collecting stats about individual trainers.

**Comment by pogo-excalibur** [comment]
That would still be fairly easy to tie back to individuals, e.g. by waiting until someone places a pokemon into a gym and then noting down their ID. And once you have someone's ID you can continue to track them.

**Comment by sebastienvercammen** [comment]
@123FLO321 Trainer ID or any form of (pseudo-)identity doesn't solve all privacy problems.

That being said, nothing is stopping us from starting a table for statistics and storing anonymous statistics rather than individual data.

This new table would also solve the problem of stats being cleared/adjusted if you use the DB cleanup routine, and it would reduce processing cost/overhead to retrieve the stats.

**Comment by riddle** [comment]
Thank you for doing this. There has been an incident in our city where a person was stalking their ex using gym history. They got so good at it, the victim was in a constant state of panic and finally the police was dragged into the situation. Super ugly. I’ve always advocated that this data should disappear and I hope EU will go down hard on those who fork RocketMap and bring back this feature.

Speaking of which, can you modify your license to prevent forks?

**Pull request merged**
