### PR TITLE
Bundle+Extract non-copyrighted sprites if not already downloaded

### PR DESCRIPTION
**Pull request by FrostTheFox**
Modifies sprite check to download the non-copyright sprites if sprite files not found.
## Description

Adds a get_sprites function to utils.py, downloads sprites from server and extracts to static, then deletes the leftover zip.
## Motivation and Context

Solve git conflict issues

## How Has This Been Tested?

Ran in Windows 10, python 2.7.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the code style of this project.

### CODE REVIEW

**Comment by FrostTheFox** [comment]
@Alderon86 Nope, it's the non-copyright sprites, which are only rev 1 :)

(notice the /RM, the normal sprites are just at /)

**Comment by Alderon86** [comment]
then i havent said anything

**Comment by onilton** [comment]
@FrostTheFox Done the other PR you talked about :

#1865

**Comment by FrostTheFox** [comment]
@onilton Seb and I talked and we agreed on not downloading, but we're going to bundle a zip with the repo, which makes my code even simpler because it just will extract and delete it.

**Comment by Obihoernchen** [comment]
Throws: `TypeError: 'module' object is not callable`. Fix: #1878

**Comment by onilton** [comment]
@Obihoernchen @FrostTheFox @sebastienvercammen I think FrostTheFox forgot to remove the files from /icons/*.png. Should I open a PR to remove it?

**Comment by Obihoernchen** [comment]
@onilton ahh that's why I got some git merge issues. I didn't really dig into it though.. Yes please :+1:

**Pull request merged**
