### PR TITLE
Hash key status page (-PS)

### PR DESCRIPTION
**Pull request by hokiepokedad**
## Description
Display the remaining, maximum and peak amount of requests left for all hash key when print-status is enabled.  The asterisk(*) appended to the hash key marks which one is currently active.  You will be able to see a new option to switch to the Hash Key status page by entering 'H' and pressing ENTER.

If multiple hash keys are specified in the CLI or config file, they will all be listed on the Hash Key status page and will display the running numbers in near real-time.

## Motivation and Context
We need a way to track how many requests are available for the current minute.

## How Has This Been Tested?
Tested on 26 scan instances running multiple hash keys.

## Screenshots (if appropriate):
screenshot 2017-01-20 14 57 22

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by kbtbc** [comment]
This looks like a great PR, however I don't understand the need for hundreds of lines of changes of simply 'formatting'   This makes it harder to review the actual code when also having to review a few hundred lines with no changes in github.

**Comment by sebastienvercammen** [comment]
@kbtbc As mentioned before, all of the edited lines are due to code style edits by autopep8.

We actually require all new edits to use flake8 and autopep8, but this hasn't been done for all old files. Everyone who has actively been participating knows this. I'm not sure what your comment tried to accomplish...

**Comment by hokiepokedad** [comment]
@sebastienvercammen thanks for the clarification on lines changed!

@kbtbc you can see @sebastienvercammen 's description of his fixes in his comment.  if you'd like to see the changes made before autopep8, you can follow the commits.  there isn't much.

**Comment by hokiepokedad** [comment]
Added additional clarification on how it supports multiple keys in the description.

**Comment by kbtbc** [comment]
I was trying to accomplish a review of the PR and was overwhelmed by differentiating between what code actually changed vs. formating only.     I suggest a separate rebase of all old code against autopep8, so that individual PRs are more simple to examine against the actual changes of made by these PR.   As @hokiepokedad suggested, I will just go back a bit in the commits.   Thank you for the explanation.

**Comment by sebastienvercammen** [comment]
@hokiepokedad My edits changed how the multiple keys work: rather than overwriting everything with N/A when they're not the active key, it will now show the last received data (if it doesn't have any, it'll show N/A).

This is an important difference because they current key scheduler distributes scans over all of the keys rather than maxing out a single key first.

**Comment by hokiepokedad** [comment]
@sebastienvercammen I see that now thanks.  I have updated the description to be inclusive of ALL keys.

**Comment by bbdoc** [comment]
Will this PR also make the info available on status page ? I'm running on a docker so using -ps is quite complicated. Status page would be more than useful. Thanks

**Comment by hokiepokedad** [comment]
Unfortunately no.  I decided to keep off the status page due to the delay in refresh intervals.  Since the remaining requests reset every minute, the number of remaining requests displayed on the status page may be delayed by about 5 seconds or more and therefore you may go over the limit due to that delay.

I believe #1676 will have that functionality however.  I was too concerned about the delay.

**Comment by bbdoc** [comment]
Thanks for your answer. What about writing peak RPM per key number every minute to the log ? I'm not really looking for a real time value, but still would like to be informed about my RPM usage so I can plan for adding new key if needed.

**Comment by hokiepokedad** [comment]
Yes, I can write that out as a new column in the hash key status page.  But you want it in the log and not the -ps page?

**Comment by bbdoc** [comment]
I want it either on the status page or in the log (or both). Reason being that accessing print-status from within a docker is quite a pity. Something like "xxx remaining out of xxx on RPM key xxxxxxx" every minute would be perfect.

**Comment by JoniValles** [comment]
This PR is just impossible to merge manually...

**Comment by sebastienvercammen** [comment]
@JoniValles Git uses patch syntax and never requires manual merging. Github is also not customer support, so please don't post comments that don't help the PR at all.

**Comment by hokiepokedad** [comment]
@bbdoc i have included a new "Peak" column to the status page that keeps track of the most requests used within the allowed rpm session. i would include these change in the log but i don't want to conflict/compete with #1699 .

**Comment by Alderon86** [comment]
@hokiepokedad i also was thinking about a peak and unused colum + changing the loginfo to something like Hash Key xxxx has xxx/xxx RPM left. Now im not sure anymore, since this would look like competing for sure

**Comment by hokiepokedad** [comment]
@Alderon86 no problem. maybe once one of ours get merged we can work together on a new PR to include that.  we should hold off on adding new features to both our PRs until they get reviewed so we can rebaseline after.

**Comment by Alderon86** [comment]
@hokiepokedad deal

**Comment by SkOODaT** [comment]
this is a great PR but it needs a realtime counter 

```
        elif display_type[0] == 'hashstatus':
            status_text.append('----------------------------------------------------------')
            status_text.append('Hash key status:')
            status_text.append('----------------------------------------------------------')

            status = '{:21} | {:9} | {:9} | {:9} | {:9}'
            status_text.append(status.format('Key', 'Remaining', 'Maximum', 'Peak', 'RealTime'))

            for key in hash_key:
                key_instance = key_scheduler.keys[key]
                key_text = key

                if key_scheduler.current() == key:
                    key_text += '*'

                status_text.append(status.format(key_text, key_instance['remaining'], key_instance['maximum'], key_instance['peak'], key_instance['real']))

                    real = key_instance['maximum'] - key_instance['remaining']
                    key_instance['real'] = real
```

**Comment by Alderon86** [comment]
@SkOODaT what you did there is the exact same thing @hokiepokedad did you just renamed peak to real

**Comment by SkOODaT** [comment]
no its not lol look again its doing somehting a bit different

**Comment by Alderon86** [comment]
@SkOODaT ah okay, thought you just were adding your lines below his peak lines

**Comment by hokiepokedad** [comment]
@SkOODaT that can certainly be added but that's just the inverse of 'remaining'.  not sure if that would be beneficial unless other would want it.

**Pull request merged**
