### PR TITLE
RM no longer supports scrubs. 

### PR DESCRIPTION
**Pull request by bluemode**
## Description
RocketMap is not longer providing documentation and basic usage information when running RM. This is an effort to cut down on questions.

## Motivation and Context
#2008 kicked my *uhhh* butt. I am bitter

## How Has This Been Tested?
Nope! That is the fun. You have to figure out how to fix it if it is broke! Good luck!

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [X] My code follows the code style of this project.
- [X] My change requires a change to the documentation.
- [X] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by FrostTheFox** [comment]
nice

**Comment by myntath** [comment]
Not sure it this was intended but my docs feel zoomier with this PR.

**Comment by sebastienvercammen** [comment]
I figured this'd be the same joke as before, but this time the details in the commits really made it, gg 👍

**Comment by SiteEffect** [comment]
Yeah, this really improved logging.

**Comment by mkruse02** [comment]
Let me start by saying I'm a long time user of this pokemongo-map and I'm a big fan of the work. I appreciate anything that will make this software run better. I do not want to see the this functionality go away. There are viable ways to utilize the docs and to remove functionality from Rocketmap seems wrong to me. The quality of the docs and the code it uses is a valuable asset and I would hate to see it lost. With all the respect I can give I ask that you please do not merge this PR. Thanks for everything you all do.

**Comment by sebastienvercammen** [comment]
Hey @mkruse02, thanks for the sincere message. @bluemode is just playing a joke, similar to his previous joke PR #1952. No worries, it's not getting merged.

Closing this before anyone else thinks it's real.

**Comment by mkruse02** [comment]
@sebastienvercammen Hahahaha, I knew it was a joke.  I'm sorry if you thought my message was "sincere", it was anything but.

**Comment by sebastienvercammen** [comment]
You dirty whores playing with my feelings like this ಠ_ಠ

**Pull request closed without merging**
