### PR TITLE
Retry failed scans

### PR DESCRIPTION
**Pull request by mew905**
## Description
As per the speed limitation, we tend to encounter lots of failed or empty scans. This attempts to fix that by simply waiting (up to 30 seconds) to scan again. Typically gets it on the second try when the speed limiter releases but the 30 second wait is for the longer speed bans. Does not reduce captcha's though, just reduces empty scans!

Noticed 1501 checks nearby to determine an empty scan vs a speed limited scan. Decided to use them and gyms to get better empty detection. Of course if a worker is far from any stops/gyms and no pokemon around, it'll count an empty.

## Motivation and Context
Tired of hundreds of empty scans. My best worker was at 50% good scans, 50% failed. With this, you can get thousands of good scans in, and only one fail.

## How Has This Been Tested?
My personal map.

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

**PS: how do you change more than one file???**

### CODE REVIEW

**Comment by SkOODaT** [comment]
awesome PR but a good modification would be to add 
```
        cday = ccost * 24
        status_text.append('Total active: {}  |  Success: {} ({}/hr) | Fails: {} | Empties: {} ({}/hr) | Skips {} | Captchas: {} ({}/hr)| [${:2}/hr]| [${:2}/dy]| [${:2}/mo]'.format(usercount, successcount, sph, failcount, emptycount, eph, skipcount, captchacount, cph, ccost, cday, cmonth))
```

**Comment by SkOODaT** [comment]
another AWESOME PR but im getting too many calls to task_done() i commented out #search_items_queue.task_done() and seems like all is ok

**Comment by mew905** [comment]
Ahhh yes... I forgot about that, good call, thank you, I'll fix it here

**Comment by iluretar** [comment]
Does this retry when captcha? i've noticed that when doing ss if the account gets captcha it gives 0/0/0 and move to the next point, retrying when captcha would be awesome.

**Comment by mew905** [comment]
1530 and 1501 as far as I know send another GMO call when solving a captcha
(that's where the conflict comes from). But yes, otherwise it'll retry
*any* time it gets a 0/0/0 with no nearby pokemon.

**Comment by kevdotcom** [comment]
Thanks for doing what I was trying to achieve :+1:  :100:

**Comment by sclo012** [comment]
@mew905 Do you know if the merged 1501 does this or not, or we have to try to merge this PR back in?

**Comment by Alderon86** [comment]
@sclo012 it does not! u want to merge this pr again, but donno if it will mess up 1501 a lot!
Would be nice if @mew905 would fix compatibility issues with latest develop <3

**Comment by DisconnectedPT** [comment]
will this work for captcha'd accounts ? meaning will it retry 0/0/0's _until_ it gets values or will it only retry once ?

**Comment by mew905** [comment]
It retries up to 3x. Captcha code attempts to solve and holds the worker
until captcha is either solved or the account gets retired, captcha check
is sent every api request now

**Comment by DisconnectedPT** [comment]
Aight thanks I have a .bat that I leave on with a loop while my accounts are scanning, it checks them for captchas and it solves them with 2captcha (pogocaptcha) and it goes through each account every 3~minutes. Do you think it retrying 3x takes long enough for the bat to go through the acc that is 0/0/0 ?

**Comment by sclo012** [comment]
Any chance of fixing the conflicts, or merging this?

**Comment by sebastienvercammen** [comment]
Closing old PR, we've had `-bsr` for a while now.

**Pull request closed without merging**
